//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoboCop5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Elkovetok
    {
        public int ELID { get; set; }
        public Nullable<int> ELSZID { get; set; }
        public Nullable<int> ELLID { get; set; }
        public Nullable<int> ELMAG { get; set; }
        public Nullable<int> ELHAJ { get; set; }
        public Nullable<int> ELSZEM { get; set; }
        public Nullable<int> ELSULY { get; set; }
        public Nullable<int> ELTERMET { get; set; }
        public Nullable<int> ELARC { get; set; }
        public Nullable<int> ELJAR { get; set; }
    
        public virtual Arcok Arcok { get; set; }
        public virtual Hajszinek Hajszinek { get; set; }
        public virtual Jarasok Jarasok { get; set; }
        public virtual Magassagok Magassagok { get; set; }
        public virtual Sulyok Sulyok { get; set; }
        public virtual Szemszinek Szemszinek { get; set; }
        public virtual Termetek Termetek { get; set; }
    }
}
