//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoboCop5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcedureLog
    {
        public int PLID { get; set; }
        public Nullable<System.DateTime> PLTIMESTAMP { get; set; }
        public int PID { get; set; }
        public int PLSUCCESSCODE { get; set; }
        public string PLARGS { get; set; }
    
        public virtual Procedures Procedures { get; set; }
    }
}
