//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;

namespace RoboCop5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users()
        {
            this.Lopasok = new HashSet<Lopasok>();
            this.UsersRolesMapping = new HashSet<UsersRolesMapping>();
            this.UsersSchoolsMapping = new HashSet<UsersSchoolsMapping>();
        }
    
        public int UID { get; set; }
        [Required]
        [Display (Name = "Emailcím")]
        public string UEMAIL { get; set; }
        [Required]
        [Display (Name ="Belépésikód")]
        public string UCODE { get; set; }
        public string UCIPHER { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lopasok> Lopasok { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsersRolesMapping> UsersRolesMapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsersSchoolsMapping> UsersSchoolsMapping { get; set; }
    }
}
